	CREATE DATABASE CUSTOMERS
	USE CUSTOMERS
	CREATE TABLE CUSTOMER
	(
	ID INT  PRIMARY KEY,
	NAME VARCHAR(100),
	COUNTRY VARCHAR(100)
	)
	SELECT * FROM CUSTOMER
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(1,'ALLU ARJUN','US')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(2,'SAI','UK')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(3,'PRABHAS','INDIA')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(4,'NTR','INDIA')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(5,'RAM POTHI','EUROPE')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(6,'SAMANTHA','INDIA')
	INSERT INTO CUSTOMER(ID,NAME,COUNTRY) VALUES(7,'SAI TEJ','RUSSIA')
	UPDATE CUSTOMER SET NAME='JR.NTR' WHERE NAME='NTR'
	DELETE FROM CUSTOMER WHERE ID=6

	CREATE TABLE SALEPRODUCTS
	(
	SID INT  PRIMARY KEY,
	NAME VARCHAR(100),
	COUNTRY VARCHAR(100),
	ID INT FOREIGN KEY REFERENCES CUSTOMER(ID)
	)
	INSERT INTO SALEPRODUCTS(SID,NAME,ID,COUNTRY) VALUES(1001,'BOOK',1,'INDIA')
	INSERT INTO SALEPRODUCTS(SID,NAME,ID,COUNTRY) VALUES(1002,'BOOK',2,'US')
	INSERT INTO SALEPRODUCTS(SID,NAME,ID,COUNTRY) VALUES(1003,'PEN ',3,'UK')
	INSERT INTO SALEPRODUCTS(SID,NAME,ID,COUNTRY) VALUES(1004,'BAG',4,'RUSSIA')
	

	SELECT NAME 
	FROM CUSTOMER
	UNION 
	SELECT NAME 
	FROM SALEPRODUCTS

	SELECT NAME 
	FROM CUSTOMER
	INTERSECT 
	SELECT NAME
	FROM SALEPRODUCTS

	SELECT NAME FROM CUSTOMER ORDER BY NAME OFFSET 2 ROWS FETCH NEXT 3 ROWS ONLY
	SELECT NAME FROM SALEPRODUCTS ORDER BY NAME OFFSET 0 ROWS FETCH NEXT 2 ROWS ONLY ;

	EXEC SP_RENAME 'CUSTOMER.ID', 'CID';