CREATE DATABASE USERDATA
USE USERDATA

CREATE TABLE STUDENT(
ID INT,
NAME VARCHAR(100),
MARKS INT,
COUNTRY VARCHAR(100))

INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(1,'RAM',90,'US')
INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(2,'KRISHNA',91,'US')
INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(3,'ALLU ARJUN',90,'UK')
INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(4,'ANUSHKA',92,'US')
INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(5,'SAMANTHA',90,'US')
INSERT INTO STUDENT(ID,NAME,MARKS,COUNTRY) VALUES(6,'PARUSHURAM',90,'US')

CREATE FUNCTION GETNAMEBYID(@ID INT)
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @NAME VARCHAR(100)
SELECT @NAME =NAME FROM STUDENT WHERE ID=@ID
RETURN @NAME
END;
SELECT dbo.GETNAMEBYID(2);

CREATE FUNCTION GETMIN()
RETURNS VARCHAR(100)
AS
BEGIN
DECLARE @MARKS INT
DECLARE @NAME VARCHAR(100)
SET @MARKS =(SELECT MIN(MARKS) FROM STUDENT)
SELECT @NAME=NAME FROM STUDENT WHERE MARKS=@MARKS
RETURN @NAME
END;
SELECT dbo.GETMIN()

CREATE PROCEDURE GETSTUDENT
@ID INT
AS
BEGIN
SELECT NAME FROM STUDENT WHERE ID=@ID
END;
EXEC GETSTUDENT 1;

CREATE PROCEDURE UPDATEBYID
@ID INT,
@NAME VARCHAR(100)
AS
BEGIN
UPDATE STUDENT SET NAME=@NAME WHERE ID=@ID
END;
EXEC UPDATEBYID @NAME='RAMANUJA',
@ID=1;

CREATE PROCEDURE REMOVEBYID
@ID INT
AS
BEGIN
DELETE STUDENT WHERE ID=@ID
END;
EXEC REMOVEBYID 1

 --1)Select all customers along with the name and city of their country:
--Select all products along with their supplier name:
 --2)Problem: Create a stored procedure that updates a 'Products' table with the provided product name and price
--for the record that matches the provided product ID.
--3)Problem: Create a function that returns the average price of a product by taking the product ID 
--as input and calculating the average of all prices for that product. */
SELECT* FROM CUSTOMER
SELECT * FROM PRODUCTS INNER JOIN SUPPLIER
ON PRODUCTS.PRODUCTID=SUPPLIER.PRODUCTID
CREATE TABLE CUSTOMER(
CUSTOMERID INT PRIMARY KEY,
CUSTOMERNAME VARCHAR(100),
COUNTRY VARCHAR(100),
SUPPLIERID INT FOREIGN KEY REFERENCES SUPPLIER(SUPPLIERID))
INSERT INTO CUSTOMER(CUSTOMERID,CUSTOMERNAME,COUNTRY,SUPPLIERID) VALUES(1001,'RAMA','INDIA',10)
INSERT INTO CUSTOMER(CUSTOMERID,CUSTOMERNAME,COUNTRY,SUPPLIERID) VALUES(1002,'SAI','US',11)

CREATE TABLE SUPPLIER(
SUPPLIERID INT PRIMARY KEY,
SUPPLIERNAME VARCHAR(100),
PRODUCTID INT FOREIGN KEY REFERENCES PRODUCTS(PRODUCTID)
)
INSERT INTO SUPPLIER(SUPPLIERID,SUPPLIERNAME,PRODUCTID) VALUES(10,'PARUSHURAMA',1)
INSERT INTO SUPPLIER(SUPPLIERID,SUPPLIERNAME,PRODUCTID) VALUES(11,'KRISHNA',2)
SELECT * FROM SUPPLIER
CREATE TABLE PRODUCTS(
PRODUCTID INT PRIMARY KEY,
NAME VARCHAR(100),
PRICE INT)
INSERT INTO PRODUCTS(PRODUCTID,NAME,PRICE) VALUES(1,'BOOK',100)
INSERT INTO PRODUCTS(PRODUCTID,NAME,PRICE) VALUES(2,'BAG',120)
INSERT INTO PRODUCTS(PRODUCTID,NAME,PRICE) VALUES(3,'COVER',10)
INSERT INTO PRODUCTS(PRODUCTID,NAME,PRICE) VALUES(4,'FLOWER',120)
SELECT * FROM PRODUCTS
CREATE PROCEDURE UPDATEPRODUCT
@NAME VARCHAR(100),
@ID INT,
@PRICE INT
AS
BEGIN
UPDATE PRODUCTS SET NAME=@NAME,PRICE=@PRICE WHERE PRODUCTID=@ID
END;
EXEC UPDATEPRODUCT @NAME='KESARI',@PRICE=100 ,@ID=3

CREATE FUNCTION GETPRICE()
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @AVERAGE DECIMAL(10,2)
SELECT @AVERAGE=AVG(PRICE) FROM PRODUCTS 
RETURN @AVERAGE
END;
SELECT dbo.GETPRICE()

CREATE FUNCTION GETPRICE1(@PRODUCTID INT)
RETURNS DECIMAL(10,2)
AS
BEGIN
DECLARE @AVERAGE DECIMAL(10,2)
SELECT @AVERAGE=AVG(PRICE) FROM PRODUCTS WHERE ID=@ID
RETURN @AVERAGE
END;
SELECT dbo.GETPRICE1(2);
