CREATE DATABASE BRIDGELABZ;

USE BRIDGELABZ

CREATE TABLE ACTOR(
ID INT NOT NULL IDENTITY(1,1),
FIRSTNAME VARCHAR(100),
SECONDNAME VARCHAR(100),
SALARY INT NOT NULL
)

SELECT * FROM ACTOR

INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('PRABHAS','H',100000)
INSERT INTO ACTOR(FIRSTNAME,SECONDNAME,SALARY) VALUES('RAM','S',1000000)
INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('SAI','TEJ',1000000000)
INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('STEEV','SAM',100000)
INSERT INTO ACTOR(FIRSTNAME,SECONDNAME,SALARY) VALUES('ALLU ARJUN','S',1000000)
INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('NTR','A',1000000000)
INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('ANUSHKA','H',100000)
INSERT INTO ACTOR(FIRSTNAME,SECONDNAME,SALARY) VALUES('PURI JAHANNATH','S',1000000)
INSERT INTO ACTOR (FIRSTNAME,SECONDNAME,SALARY) VALUES('SURYA','V',1000000000)

UPDATE ACTOR SET SECONDNAME='POTHENENI' WHERE FIRSTNAME='RAM';

 DELETE FROM ACTOR WHERE ID=7;
 ALTER TABLE ACTOR
 ADD LASTNAME VARCHAR(100)
 ALTER TABLE ACTOR
 DROP COLUMN LASTNAME
 DROP TABLE ACTOR
 SELECT SECONDNAME FROM ACTOR ORDER BY SECONDNAME
 SELECT * FROM ACTOR WHERE FIRSTNAME='RAM' AND  SECONDNAME LIKE '%A%'
 SELECT * FROM ACTOR WHERE FIRSTNAME='SAI' AND SECONDNAME ='TEJ' AND SALARY>10000;
 SELECT * FROM ACTOR WHERE FIRSTNAME='RAM' AND (SECONDNAME LIKE '%A%' OR SECONDNAME LIKE'%Z')
 SELECT FIRSTNAME FROM ACTOR ORDER BY FIRSTNAME OFFSET 5 ROWS;
 SELECT SECONDNAME FROM ACTOR ORDER BY SECONDNAME OFFSET 2 ROWS FETCH NEXT 4 ROWS ONLY

 SELECT DISTINCT SECONDNAME FROM ACTOR 
 SELECT FIRSTNAME FROM ACTOR WHERE SALARY IN (100000,1000000)
 SELECT FIRSTNAME FROM ACTOR WHERE SALARY>=100000 OR SALARY=1000000 