CREATE DATABASE SUBQUERIES2
USE SUBQUERIES2

CREATE TABLE EMPLOYEE
(
ID INT,
NAME VARCHAR(100),
SALARY INT,
DEPARTMENTID INT PRIMARY KEY 
)
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENTID) VALUES(1,'ALLU ARJUN',1500,200)
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENTID) VALUES(2,'ANUSHKA',2000,201)
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENTID) VALUES(3,'SAI',1500,202)
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENTID) VALUES(4,'PARUSHURAMA',1000,203)
INSERT INTO EMPLOYEE(ID,NAME,SALARY,DEPARTMENTID) VALUES(5,'PURI',1000,204)
DROP TABLE EMPLOYEE
CREATE TABLE DEPARTMENT
(
DEPARTMENTID INT FOREIGN KEY REFERENCES EMPLOYEE(DEPARTMENTID),
DEPARTMENTNAME VARCHAR(100))
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME) VALUES(200,'IT')
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME) VALUES(201,'IT')
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME) VALUES(202,'TEACHER')
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME) VALUES(203,'TEACHER')
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME) VALUES(204,'ACTOR')
DROP TABLE DEPARTMENT

SELECT * FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

SELECT NAME FROM EMPLOYEE LEFT JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

SELECT * FROM EMPLOYEE RIGHT JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

SELECT NAME ,SALARY
FROM EMPLOYEE
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEE)

SELECT NAME,
MAX(SALARY),
MIN(SALARY)
FROM EMPLOYEE
GROUP BY NAME
HAVING MAX(SALARY)>1000 

SELECT NAME,
AVG(SALARY) FROM EMPLOYEE GROUP BY NAME
HAVING AVG(SALARY) BETWEEN 500 AND 1000;

INSERT INTO GETEMPLOYEE2 VALUES(6,'RAM',10000,205,'TEACHER')

CREATE OR ALTER VIEW GETEMPLOYEE2
AS
SELECT ID,NAME,SALARY,DEPARTMENTNAME,DEPARTMENT.DEPARTMENTID FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID;
SELECT * FROM GETEMPLOYEE2

CREATE OR ALTER VIEW GETEMPLOYEE2
AS
SELECT EMPLOYEE.*,DEPARTMENTNAME FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID;
SELECT * FROM GETEMPLOYEE2

CREATE OR ALTER VIEW INFO
AS
SELECT EMPLOYEE.*,DEPARTMENT.DEPARTMENTNAME
FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTNAME='HR'
SELECT * FROM INFO
DROP VIEW INFO

