CREATE DATABASE QUERY
USE QUERY

CREATE TABLE EMPLOYEE
(
CUSTOMER_ID INT ,
FIRST_NAME VARCHAR(100),
COUNTRY VARCHAR(100),
DEPARTMENT VARCHAR(100),
SALARY INT 
)
SELECT * FROM EMPLOYEE
INSERT INTO EMPLOYEE(CUSTOMER_ID,FIRST_NAME,COUNTRY,DEPARTMENT,SALARY) VALUES(1,'ANUSHKA','INDIA','IT',1000)
INSERT INTO EMPLOYEE(CUSTOMER_ID,FIRST_NAME,COUNTRY,DEPARTMENT,SALARY) VALUES(2,'VIRAT','INDIA','PLAYER',1000)
INSERT INTO EMPLOYEE(CUSTOMER_ID,FIRST_NAME,COUNTRY,DEPARTMENT,SALARY) VALUES(3,'ALLU ARJUN','US','ACTOR',10000)
INSERT INTO EMPLOYEE(CUSTOMER_ID,FIRST_NAME,COUNTRY,DEPARTMENT,SALARY) VALUES(4,'PRABHAS','UK','ACTOR',1000)
INSERT INTO EMPLOYEE(CUSTOMER_ID,FIRST_NAME,COUNTRY,DEPARTMENT,SALARY) VALUES(5,'RAM','UAE','TEACHER',1000)

SELECT * FROM EMPLOYEE
SELECT SUM(SALARY) FROM EMPLOYEE
SELECT MAX(SALARY) FROM EMPLOYEE
SELECT MIN(SALARY) FROM EMPLOYEE

SELECT * FROM EMPLOYEE WHERE COUNTRY='INDIA' 
SELECT * FROM EMPLOYEE WHERE COUNTRY='INDIA' OR COUNTRY IN('UK','UAE','US') ORDER BY COUNTRY DESC

SELECT COUNTRY,DEPARTMENT FROM EMPLOYEE WHERE DEPARTMENT='IT' GROUP BY COUNTRY,DEPARTMENT HAVING DEPARTMENT='IT'

SELECT COUNTRY,DEPARTMENT FROM EMPLOYEE GROUP BY COUNTRY,DEPARTMENT HAVING DEPARTMENT='IT'

SELECT LEN(COUNTRY) FROM EMPLOYEE

SELECT * FROM EMPLOYEE ORDER BY COUNTRY OFFSET 2 ROWS
SELECT * FROM EMPLOYEE ORDER BY DEPARTMENT OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY
SELECT TOP 3 * FROM EMPLOYEE
SELECT TOP 3 WITH TIES  * FROM EMPLOYEE ORDER BY COUNTRY

SELECT DISTINCT(COUNTRY) FROM EMPLOYEE

SELECT *
FROM EMPLOYEE
WHERE COUNTRY='INDIA'

SELECT * 
FROM EMPLOYEE
WHERE COUNTRY='INDIA' AND SALARY=1000

SELECT *
FROM EMPLOYEE
WHERE COUNTRY='INDIA' OR SALARY=1000

SELECT * 
FROM EMPLOYEE 
WHERE SALARY BETWEEN 1000 AND 10000

SELECT *
FROM EMPLOYEE
WHERE COUNTRY LIKE'%INDIA%'