CREATE DATABASE EMPLOYEE
USE EMPLOYEE

CREATE TABLE EMPLOYEES
(
ID INT NOT NULL,
NAME VARCHAR(100),
COUNTRY VARCHAR(100),
)
SELECT * FROM EMPLOYEES
INSERT INTO EMPLOYEES(ID,NAME,COUNTRY) VALUES(1,'RAM','INDIA')
INSERT INTO EMPLOYEES(ID,NAME,COUNTRY) VALUES(2,'SAI','INDIA')
INSERT INTO EMPLOYEES(ID,NAME,COUNTRY) VALUES(3,'PRAHAS','INDIA')
INSERT INTO EMPLOYEES(ID,NAME,COUNTRY) VALUES(4,'ALLU ARJUN','INDIA')
INSERT INTO EMPLOYEES(ID,NAME,COUNTRY) VALUES(5,'PURI','INDIA')

UPDATE EMPLOYEES SET NAME='NTR' WHERE NAME='PURI'
DROP TABLE EMPLOYEES

ALTER TABLE EMPLOYEES
ADD EMAIL VARCHAR

EXEC SP_RENAME 'EMPLOYEES.EMAIL','EMAILID';

DELETE FROM EMPLOYEES WHERE NAME='SAI';
TRUNCATE   TABLE EMPLOYEES 

SELECT DISTINCT COUNTRY  FROM EMPLOYEES ;
SELECT COUNT(DISTINCT COUNTRY) FROM EMPLOYEES;
SELECT  * FROM EMPLOYEES ORDER BY NAME;
SELECT  * FROM EMPLOYEES ORDER BY NAME DESC;
SELECT * FROM EMPLOYEES ORDER BY NAME ASC,ID DESC;