CREATE DATABASE SUBQUERY
USE SUBQUERY

CREATE TABLE ORDERS
(
ORDERID INT ,
CUSTOMERID INT PRIMARY KEY,
PRICE INT
)
SELECT * FROM ORDERS
INSERT INTO ORDERS(ORDERID,CUSTOMERID,PRICE) VALUES(1,1001,1000)
INSERT INTO ORDERS(ORDERID,CUSTOMERID,PRICE) VALUES(2,1002,10000)
INSERT INTO ORDERS(ORDERID,CUSTOMERID,PRICE) VALUES(3,1003,10000)
INSERT INTO ORDERS(ORDERID,CUSTOMERID,PRICE) VALUES(4,1004,1000)

CREATE TABLE CUSTOMER(
CUSTOMERID INT FOREIGN KEY REFERENCES ORDERS(CUSTOMERID),
NAME VARCHAR(100) ,
CITY VARCHAR(100),
COUNTRY VARCHAR(100)
)
INSERT INTO CUSTOMER(CUSTOMERID,NAME,CITY,COUNTRY) VALUES(1001,'SAI','PURI','INDIA')
INSERT INTO CUSTOMER(CUSTOMERID,NAME,CITY,COUNTRY) VALUES(1002,'RAM','MYSORE','INDIA')
INSERT INTO CUSTOMER(CUSTOMERID,NAME,CITY,COUNTRY) VALUES(1003,'SAMANTHA','MYSORE','UK')

SELECT ORDERID,
CUSTOMERID
FROM 
ORDERS
WHERE
CUSTOMERID IN(
SELECT 
CUSTOMERID 
FROM 
CUSTOMER
WHERE COUNTRY='INDIA'
)


SELECT  MAX(PRICE)  AS PRICE
FROM ORDERS
WHERE CUSTOMERID=(
SELECT CUSTOMERID
FROM
CUSTOMER
WHERE CITY IN('PURI'))

SELECT *
FROM ORDERS
WHERE EXISTS(
SELECT *
FROM ORDERS
WHERE CUSTOMERID=1001)

SELECT COUNT(PRICE) AS COUNT 
FROM ORDERS
