CREATE DATABASE SUBQUERIES
USE SUBQUERIES

CREATE TABLE EMPLOYEE(
EID INT,
NAME VARCHAR(100),
SALARY INT,
DEPARTMENTID INT PRIMARY KEY
)
INSERT INTO EMPLOYEE(EID,NAME,SALARY,DEPARTMENTID) VALUES(1,'VIRAT',10000,1001)
INSERT INTO EMPLOYEE(EID,NAME,SALARY,DEPARTMENTID) VALUES(2,'ANUSHKA',10000,1002)
INSERT INTO EMPLOYEE(EID,NAME,SALARY,DEPARTMENTID) VALUES(3,'PARUSHURAMA',10000,1003)
INSERT INTO EMPLOYEE(EID,NAME,SALARY,DEPARTMENTID) VALUES(4,'SAI',1000000,1005)

CREATE TABLE DEPARTMENT(
DEPARTMENTID INT FOREIGN KEY REFERENCES EMPLOYEE(DEPARTMENTID),
DEPARTMENTNAME VARCHAR(100),CITY VARCHAR(100)
)
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME,CITY) VALUES(1001,'IT','US')
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME,CITY) VALUES(1002,'ACTOR','UK')

--SELECT ALL EMPLOYEE WHO WORK IN DEPARTMENT WITH A TOTAL SALARY GREATER THAN 5000

SELECT * FROM EMPLOYEE WHERE DEPARTMENTID=(
SELECT DEPARTMENTID FROM DEPARTMENT WHERE SALARY IN(10000))

SELECT * FROM EMPLOYEE 
WHERE SALARY>=500

SELECT EMPLOYEE.DEPARTMENTID,SALARY
FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID GROUP BY EMPLOYEE.DEPARTMENTID,SALARY HAVING SUM (SALARY)>500 

--SELECT ALL DEATILS OF EMPLOYEE ALONG WITH THE NAME AND CITY OF THEIR DEPARTMENT
SELECT * 
FROM EMPLOYEE INNER JOIN DEPARTMENT
ON EMPLOYEE.DEPARTMENTID=DEPARTMENT.DEPARTMENTID

--SELECT ALL ORDERS ALONG WITH THE NAME OF THE CUSTOMER WHO PLACED THE ORDER

CREATE TABLE ORDERS
(
ID INT,
CUSTOMERID INT PRIMARY KEY,

)
INSERT INTO ORDERS(ID,CUSTOMERID) VALUES(1,1001)
INSERT INTO ORDERS(ID,CUSTOMERID) VALUES(2,1002)
INSERT INTO ORDERS(ID,CUSTOMERID) VALUES(3,1003)
INSERT INTO ORDERS(ID,CUSTOMERID) VALUES(4,1004)

CREATE TABLE CUSTOMER(
CUSTOMERID INT FOREIGN KEY REFERENCES ORDERS(CUSTOMERID),
NAME VARCHAR(100))
INSERT INTO CUSTOMER(CUSTOMERID,NAME) VALUES(1001,'SAI')
INSERT INTO CUSTOMER(CUSTOMERID,NAME) VALUES(1002,'RAM')

SELECT * FROM ORDERS INNER JOIN CUSTOMER
ON ORDERS.CUSTOMERID=CUSTOMER.CUSTOMERID

 
